"""empty message

Revision ID: 540d4b33cf2f
Revises:
Create Date: 2019-12-20 11:02:44.300136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "540d4b33cf2f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("author", sa.String(length=500), nullable=True),
        sa.Column("year", sa.String(length=4), nullable=True),
        sa.Column("identifiers_json", sa.String(length=500), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("isbn_10", sa.String(length=25), nullable=True),
        sa.Column("isbn_13", sa.String(length=25), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_book_source_id"), "book", ["source_id"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("date_added", sa.Date(), nullable=True),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "user_id"),
    )
    op.create_index(op.f("ix_plan_date_added"), "plan", ["date_added"], unique=False)
    op.create_table(
        "reading",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("date_started", sa.Date(), nullable=True),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "user_id"),
    )
    op.create_index(op.f("ix_reading_book_id"), "reading", ["book_id"], unique=False)
    op.create_index(
        op.f("ix_reading_date_started"), "reading", ["date_started"], unique=False
    )
    op.create_index(op.f("ix_reading_user_id"), "reading", ["user_id"], unique=False)
    op.create_table(
        "review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_text", sa.Text(), nullable=True),
        sa.Column("date_read", sa.Date(), nullable=True),
        sa.Column("did_not_finish", sa.Boolean(), nullable=True),
        sa.Column("is_favourite", sa.Boolean(), nullable=True),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_date_read"), "review", ["date_read"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_date_read"), table_name="review")
    op.drop_table("review")
    op.drop_index(op.f("ix_reading_user_id"), table_name="reading")
    op.drop_index(op.f("ix_reading_date_started"), table_name="reading")
    op.drop_index(op.f("ix_reading_book_id"), table_name="reading")
    op.drop_table("reading")
    op.drop_index(op.f("ix_plan_date_added"), table_name="plan")
    op.drop_table("plan")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_book_source_id"), table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###
