"""empty message

Revision ID: e9aa8ecc650d
Revises: 27c9b875bd59
Create Date: 2019-12-17 13:08:23.017083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9aa8ecc650d'
down_revision = '27c9b875bd59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_address', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_address')
    # ### end Alembic commands ###
